os: linux
dist: trusty

before_install:
  - cd /opt
  - wget https://www.cpan.org/src/5.0/perl-5.32.1.tar.gz
  - tar -xzf perl-5.32.1.tar.gz
  - cd perl-5.32.1
  - ./Configure -de
  - sudo make
  - sudo make test
  - sudo make install
script:
  - perl -v
  - perl test.pl